### ISSUE TITLE
Yojson.Json_error is raised.

### ISSUE THREAD

**Issue by nomaddo** [mjambon/yojson#16]
Hi,

When I try to use yojson, I had a trouble when I got  json via socket. like following programs.
When I send a json to a local server twice,  `Fatal error: exception Yojson.Json_error` raised.
Nothing raised when I send a json only once.
Is it a bug or did I misunderstood how to use it ?

server.ml

    let parse json =
      match json with
      | `List l -> l
      | _ -> assert false

    let () =
      let addr = Unix.ADDR_INET (Unix.inet_addr_of_string "127.0.0.1", 3300) in
      Unix.establish_server (fun ic oc ->
          let f () =
            let json = Yojson.Safe.from_channel ic in
            parse json
            |> List.length
            |> print_int in
          f (); f ()
        ) addr

client.ml

    let () =
      let addr = Unix.ADDR_INET (Unix.inet_addr_of_string "127.0.0.1", 3300) in
      let ic, oc = Unix.open_connection addr in
      let json = Array.init 100 (fun i -> `Int i)
                 |> Array.to_list |> (fun l -> `List l) in
      Yojson.Safe.to_channel oc json;
      flush oc;
      Yojson.Safe.to_channel oc json;
      flush oc

execution log

      [~/ocaml/json] ocamlfind query yojson -format %v
    1.2.0

     [~/ocaml/json] ./server & 
    [4] 48638
    [~/ocaml/json] ./clinet 
    [~/ocaml/json] Fatal error: exception Yojson.Json_error("Line 1, bytes 292-324:\nJunk after end of JSON value: '[0,1,2,3,4,5,6,7,8,9,10,11,12,13,'")
    Raised at file "common.ml", line 5, characters 25-39
    Called from file "read.mll", line 1105, characters 6-21
    Called from file "read.mll", line 1122, characters 6-26
    Called from file "server.ml", line 10, characters 19-46
    Called from file "server.ml", line 14, characters 6-10
    Called from file "unix.ml", line 1081, characters 12-37
    Called from file "server.ml", line 8, characters 2-198

**Comment by mjambon** [comment]
Sorry for the late reply.

`from_channel` can only be used to read from a channel that provides a single value.

In order to read multiple value from a channel, use `stream_from_channel`, which gives you a stream from which you can pull json values.
