### ISSUE TITLE
Integer overflow with certain responses on 32-bit platforms

### ISSUE THREAD

**Issue by eras** [mjambon/yojson#18]
In particular, chat_send_message caused issues for me, on Raspberry Pi.

This would be resolved by refraining to use Yojson.Basic-module that does integer conversions always, whereas Yojson.Safe uses Intlit in case of integer overflow.

**Comment by dsheets** [comment]
Belongs on [Leonidas-from-XIV/slacko](https://github.com/Leonidas-from-XIV/slacko/issues)?

**Comment by eras** [comment]
You know you're completely correct, but as I was first considering adding int64-support to Yojson I had the wrong site open. I was actually wondering where did the issue go.. :-).
