### ISSUE TITLE
use standard types for IO

### ISSUE THREAD

**Issue by c-cube** [mjambon/yojson#24]
Would it be possible to provide `Format` compatible printers directly, such as `Yojson.Safe.print : Format.formatter -> json -> unit`? It is more convenient and direct than using easy-format, and would possibly allow to get rid of the dependency on easy-format…

**Comment by mjambon** [comment]
We can add a function that writes json to a `Format.formatter`, as a convenience (into this file: https://github.com/mjambon/yojson/blob/master/write2.mli).

This won't get rid of the dependency on easy-format. As it depends only on the standard library (`Format` module), it shouldn't be a problem to install it.
