### ISSUE TITLE
By default Error should contain the line number/character position of error.

### ISSUE THREAD

**Issue by jordwalke** [mjambon/yojson#33]
Right now, it gives an error merely describing the type that was not formed correctly. In addition, I think it should tell you where the error was in the json input.

**Comment by mjambon** [comment]
The creation of a new position object is disabled in the lexer (by shadowing the [`Lexing` module](https://github.com/mjambon/yojson/blob/master/lib/read.mll)), allowing a 31% speed gain according to the note in that file. The disadvantage of this is we don't store location objects along the yojson AST. As a result, we can't print location when an error occurs while browsing the yojson AST.

Keep in mind that yojson was designed as a runtime library for atdgen and as a fallback for dealing with untypable json.

**Comment by abishekvashok** [comment]
@mjambon have you guys thought of a way to enable it parametrically (ie, off by default, and then you can also turn it on? )

**Comment by c-cube** [comment]
This is changeable at runtime and per-lexbuf, so it could be enabled optionally. I imagine the parser could even check whether `Lexing.with_positions lexbuf` and produce locations only if it's true.

**Comment by abishekvashok** [comment]
@c-cube ah that's interesting. I am kind of a OCaml beginner, and would appreciate if you could elaborate a bit more on how to do it :)

**Comment by c-cube** [comment]
I don't think there's any provision for it in yojson currently, given that the JSON types contain no location information. But typically if you give yojson a lexbuf and it fails to parse you can look at `lexbuf.Lexing.lex_curr_p` for the last position it used.

**Comment by abishekvashok** [comment]
@c-cube tried something similar with `Bi_outbuf` and it works! Thanks.

**Comment by Leonidas-from-XIV** [comment]
Keep in mind that `Bi_outbuf` is gone on the master branch and the next release will not feature it anymore.

**Comment by abishekvashok** [comment]
@Leonidas-from-XIV ah no! Is there any other way I could get a line number?
