### ISSUE TITLE
Wrong file naming error YoJson when Yojson was expected

### ISSUE THREAD

**Issue by mfrawley** [mjambon/yojson#38]
Trying to get this working on OSX 10.12.3. 

I've tried switching and un/installing 4.04 and 4.02.3 (my system version):
```
corebuild -r -pkg core -pkg yojson test.native
```
I get the following:
```
Error: Wrong file naming: /Users/blah/.opam/system/lib/yojson/yoJson.cmi
contains the compiled interface for 
YoJson when Yojson was expected
Command exited with code 2.
Compilation unsuccessful after building 2 targets (1 cached) in 00:00:00.
```

Note, using ocamlbuild directly gives me the same error.

**Comment by mjambon** [comment]
This has to come from something outside of yojson. I never use camelCase for new OCaml identifiers.

Feel free to reopen the issue if there's a bad interaction with some public component.
