### ISSUE TITLE
Unable to compile with under OCaml 4.07 / MSVC2017 64

### ISSUE THREAD

**Issue by Enzojz** [mjambon/yojson#59]
Error given:
File "type.ml", line 8, characters 2-3:
Error: Syntax error

Compiles under 4.06

**Comment by Enzojz** [comment]
use jbuilder with package, or directly ocamlc, both give the same error.
I don't have opam, since I think it doesn't work under windows with msvc and without cygwin(my requirement)

**Comment by mjambon** [comment]
It could be due to this: https://github.com/mjambon/cppo/pull/52, i.e. for ocaml >= 4.07 you need cppo >= 1.6.1. You can check that with `cppo -version`.

**Comment by Enzojz** [comment]
This DO work. Thank you. `cppo -version` helps me out

In fact I found an old version cppo under my cygwin/usr/local/bin, which overrides the recent version I built under OCaml/bin
