### ISSUE TITLE
Don't ignore exceptions

### ISSUE THREAD

**Issue by mjambon** [mjambon/yojson#62]
#61 was a bug that was hard to fix because an exception coming from another library was not reported and instead `Failure "oops"` (sic) was raised.

This task is to make sure that any exception that's caught is reported, translated accurately, or re-raised.

**Comment by NathanReb** [comment]
I have my local fix for #61 seating somewhere, I can probably work something out from there!

**Comment by mjambon** [comment]
@NathanReb that would be great!
